-- NOT NULL by rule, and no default: its value comes from attidentity, not
-- pg_attrdef. Getting either half wrong made this table unconvergeable.
CREATE TABLE t (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    n  int    GENERATED ALWAYS AS IDENTITY
);
