-- Fixture for the live PostgreSQL integration tests.
--
-- Run against an EMPTY database; scripts/test-fixture.sh creates one and calls
-- this. Everything the tests in tests/Strata.Tests/CatalogIntrospectionTests.fs
-- assert about is here, and nothing else — a fixture with spare objects invites
-- tests that depend on them without saying so.
--
-- Two roles matter. Objects are created as `strata`, the role the tests connect
-- as; the `hidden` schema is created as the superuser and never granted, which
-- is the whole point of it. PostgreSQL's catalog is world-readable, so
-- hidden.secret is VISIBLE to the test role and not READABLE by it. That is the
-- distinction EV-STRATA-2026-E7A9 corrected the notebook on, and the only way
-- to test it is to have such an object.

-- ---- the readable half, owned by the test role ----------------------------

SET ROLE strata;

CREATE SCHEMA sales;

CREATE TABLE sales.customer (
    id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL
);

-- Exactly one foreign key: `a foreign key is discovered with its referenced
-- table and columns` asserts Single on this table's foreign keys.
CREATE TABLE sales.orders (
    order_id    bigint        GENERATED BY DEFAULT AS IDENTITY,
    customer_id bigint        NOT NULL,
    status      text          NOT NULL DEFAULT 'open',
    total       numeric(12,2) NOT NULL DEFAULT 0,
    CONSTRAINT pk_orders PRIMARY KEY (order_id),
    CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id) REFERENCES sales.customer (id),
    CONSTRAINT ck_orders_total_nonneg CHECK (total >= 0)
);

-- Partial: `a partial index retains its predicate` fails if this has no WHERE.
CREATE INDEX idx_orders_open ON sales.orders (customer_id) WHERE status = 'open';

CREATE VIEW sales.v_open_orders AS
    SELECT order_id, customer_id, total
    FROM sales.orders
    WHERE status = 'open';

-- Language `sql` specifically: the routine test asserts it.
CREATE FUNCTION sales.order_count(p_customer bigint) RETURNS bigint
    LANGUAGE sql
    AS $$ SELECT count(*) FROM sales.orders WHERE customer_id = p_customer $$;

-- A trigger, so the `triggers` completeness category has something to report
-- and is exercised rather than merely succeeding on an empty table.
CREATE FUNCTION sales.touch_orders() RETURNS trigger
    LANGUAGE plpgsql
    AS $$ BEGIN RETURN NEW; END $$;

CREATE TRIGGER trg_orders_touch
    BEFORE UPDATE ON sales.orders
    FOR EACH ROW
    EXECUTE FUNCTION sales.touch_orders();

RESET ROLE;

-- ---- the unreadable half, never granted to the test role ------------------
--
-- No GRANT follows, deliberately. `an unreadable object makes relation_access
-- Partial, never Complete` depends on the test role having no USAGE here.

CREATE SCHEMA hidden;

CREATE TABLE hidden.secret (
    id    bigint PRIMARY KEY,
    token text NOT NULL
);
